### ISSUE TITLE
Ensure valid context before merging

### ISSUE THREAD

**Issue by dstepe** [nipwaayoni/elastic-apm-php-agent#23]
Reported here:

https://github.com/philkra/elastic-apm-php-agent/issues/119

There is probably an opportunity to switch from arrays to real objects for managing contexts as well.

**Comment by tsantos84** [comment]
Seems to me that ElasticAPM has a strong typed contract and I think we should enforce it on our side.

**Comment by dstepe** [comment]
Agreed. I added some basic json schema validation testing for exactly this reason. It makes a lot of sense to align with APM. It's going to take some work, but we should build a road map for releases that includes this.

**Comment by dstepe** [comment]
I believe this is functionally resolved, but the issue was never closed.
