### ISSUE TITLE
Make it easier to send system metrics (cpu/mem) with apm

### ISSUE THREAD

**Issue by science695** [nipwaayoni/elastic-apm-php-agent#41]
APM's requests that all agents send metrics on cpu and memory.

I had been looking around and having difficulty finding these options. I finally managed to piece some details together:

- Example of json to send metric: https://discuss.elastic.co/t/intake-api-memory-usage-metricset-does-not-recieve-data/200247/5
-Elastic's list of metric keys to send the data: https://github.com/elastic/apm/blob/master/docs/agents/agent-development.md#systemprocess-cpuheap

And then I finally found the example page in the docs for this agent: https://github.com/nipwaayoni/elastic-apm-php-agent/blob/7162481bd9f8164e4396f8438cfecc010d6a6a1c/docs/examples/metricset.php#L21

For the mean time, I will be using these resources to manually send metrics in my applications.

Does anyone else think that automatically sending those metrics would make sense? (the official agents all send them, but not sure about the interval)

Or in the least, a helper to trigger the metrics being sent rather then the application having to gather and send them.

**Comment by science695** [comment]
I think I have found the full reason why this isn't mainstream in php: No standardized way to collect system cpu/mem information in php.

**Comment by dstepe** [comment]
The metric event is unchanged the previous version of this module. I intend to put together a roadmap for some releases that improve alignment with the APM agent guidelines, including metrics as described here:

https://github.com/elastic/apm/blob/master/docs/agents/agent-development.md#metrics

I expect sending metrics by default makes sense, but allowing it to be disabled.

While there may be no 'standardized' way to collect CPU and memory data in PHP, it is possible and we can provide an extensible framework to do it in the package.

**Comment by science695** [comment]
I've also been looking, but not having much success on trying to get metrics from metricbeat, but I have yet to find anything discussing how you would combine metricbeat records with apm.

I suppose you could have metricbeat log the last few records to a file (with a very small rotate size), and then pull the last couple lines from that file.
