### ISSUE TITLE
Use async request to send data to APM

### ISSUE THREAD

**Issue by dstepe** [nipwaayoni/elastic-apm-php-agent#49]
Look at using `\Http\Client\HttpAsyncClient::sendAsyncRequest()` rather than `\Psr\Http\Client\ClientInterface::sendRequest()`. This would allow the Agent to return control without waiting for APM to respond.

**Comment by tsantos84** [comment]
I think it'd a very nice addition to the agent. My only concern is that we need to handle exceptions in case of failures when calling `sendAsyncRequest`

**Comment by dstepe** [comment]
I don't think this will be easy to implement. The work can remain on the branch to be picked up later if anyone is interested, but at this point, there does not appear to be any real demand anyway.
