### ISSUE TITLE
Subclassing Agent is prohibitive due to build complexity

### ISSUE THREAD

**Issue by dstepe** [nipwaayoni/elastic-apm-php-agent#54]
The changes to how the agent is constructed make it challenging to extend the `Agent` class. The `AgentBuilder` always creates a new `Agent` object, so any project needing to extend the Agent is left to handle the construction without the builder.

**Comment by tsantos84** [comment]
Fixed on https://github.com/nipwaayoni/elastic-apm-php-agent/pull/59
