### ISSUE TITLE
Transaction not getting associated with Errors on Elastic Cloud APM

### ISSUE THREAD

**Issue by abhishek1234graphs** [nipwaayoni/elastic-apm-php-agent#78]
If you notice the latest intake/v2/events Error schema on https://www.elastic.co/guide/en/apm/guide/current/api-error.html, along with the `transaction_id`, a `transaction` object should also be present in the incoming JSON. 
Now in `jsonSerialize` function of `Nipwaayoni\Events\Error`, the `transaction` key is not present. Therefore this key is never included during API calls made to Elastic Cloud APM Server.
I called the API with and without the `transaction` key - the resulting Error (captured using `captureThrowable` function) got associated with a Transaction only if this key is included in the request body. Without the inclusion of this key, the Transaction correctly displays the presence of an Error, but never really redirects to the Error upon trying to inspect the associated Error separately (when you click on "View related error" on the Transaction).
Is it possible for you to upgrade `Nipwaayoni\Events\Error` to appropriately include this new Schema?

**Comment by dstepe** [comment]
Thanks for bringing this up. I won't be able to look at updating the package to support the 8.3 schema for a couple of days, and cannot provide an estimate on when it may be complete. I'd like to review the new schema for more than just the issue you identified with the error object. I will look at it when I have an opportunity, though.

**Comment by abhishek1234graphs** [comment]
@dstepe thank you for your assurance! 
I think this further explains the issue: https://github.com/elastic/apm/issues/531

**Comment by abhishek1234graphs** [comment]
@dstepe 
I think the `jsonSerialize` function of `Nipwaayoni\Events\Error` should be as follows:

```
public function jsonSerialize(): array
    {
         
 return [
            $this->eventType => array_merge(
                [
                    'id'             => $this->getId(),
                    'transaction_id' => $this->getParentId(),
                    'parent_id'      => $this->getParentId(),
                    'trace_id'       => $this->getTraceId(),
                    'timestamp'      => $this->getTimestamp(),
                    'context'        => $this->getContext(),
                    'culprit'        => Encoding::keywordField(sprintf('%s:%d', $this->throwable->getFile(), $this->throwable->getLine())),
                    'exception'      => [
                        'message'    => $this->throwable->getMessage(),
                        'type'       => Encoding::keywordField(get_class($this->throwable)),
                        'code'       => $this->throwable->getCode(),
                        'stacktrace' => $this->mapStacktrace(),
                    ],
                ]
            , $this->transactionData())
        ];
   }
```
We need to merge the inner associate array with the Transaction Data. _(Please change the placement of your `array_merge` function )_

**Comment by abhishek1234graphs** [comment]
@dstepe 
I think the `jsonSerialize` function of `Nipwaayoni\Events\Error ` should be:
```
public function jsonSerialize(): array
    {
        

    return [
            $this->eventType => array_merge(
                [
                    'id'             => $this->getId(),
                    'transaction_id' => $this->getParentId(),
                    'parent_id'      => $this->getParentId(),
                    'trace_id'       => $this->getTraceId(),
                    'timestamp'      => $this->getTimestamp(),
                    'context'        => $this->getContext(),
                    'culprit'        => Encoding::keywordField(sprintf('%s:%d', $this->throwable->getFile(), $this->throwable->getLine())),
                    'exception'      => [
                        'message'    => $this->throwable->getMessage(),
                        'type'       => Encoding::keywordField(get_class($this->throwable)),
                        'code'       => $this->throwable->getCode(),
                        'stacktrace' => $this->mapStacktrace(),
                    ],
                ]
            , $this->transactionData())
        ];
    }
```
I changed the position of the `array_merge` function.

**Comment by dstepe** [comment]
Good catch. I was clearly not paying attention. Thanks. That should be fixed if you want to give it a try.

**Comment by abhishek1234graphs** [comment]
Hi @dstepe !
Good job transforming the code to fix https://github.com/elastic/apm/issues/531. I have tested the add-apm-8-support branch and can verify that Transactions are now getting correlated with Errors properly on Elastic APM's latest version (that is hosted on Elastic Cloud).
Is it possible for you to merge add-apm-8-support with the main branch and publish your changes to Packagist? Just to notify you, we rely on https://github.com/arkaitzgarro/elastic-apm-laravel.
