### ISSUE TITLE
PHP 8.1 support >   strlen(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by tomvo** [nipwaayoni/elastic-apm-php-agent#81]
Hey I was wondering if the library is supposed to support 8.1 because i'm getting these kind of errors.

**Comment by dstepe** [comment]
The intent is to support PHP 8.1 and the workflow includes running the tests under PHP 8.1. However, that does not mean there is a test case which covers the specific scenario you are encountering. If you can provide more context to the error, I can start looking at.

**Comment by dstepe** [comment]
There was only one use of `strlen` in this package. Tests have been added for handling empty arguments and impacted method has been updated. I also took the time to update some dev dependencies and the GitHub actions.

**Comment by tomvo** [comment]
hey Dirk @dstepe thanks a lot for this!
