### ISSUE TITLE
"\"metadata\" or \"m\" required"

### ISSUE THREAD

**Issue by shlomo-shalev** [nipwaayoni/elastic-apm-php-agent#88]
I get:
{"log.level":"error","@timestamp":"2024-11-07T10:13:56.515Z","log.logger":"request","log.origin":{"file.name":"middleware/log_middleware.go","file.line":58},"message":"data validation error","service.name":"apm-server","url.original":"/intake/v2/events","http.request.method":"POST","user_agent.original":"elasticapm-php/8.2.0","source.address":"172.18.0.8","http.request.id":"e4a2ea09-6297-437d-a766-810536bae8dc","event.duration":328924,"http.response.status_code":400,"error.message":"\"metadata\" or \"m\" required","ecs.version":"1.6.0"}
from apm server.

**Comment by shlomo-shalev** [comment]
I had to use a new agent object after send in laravel because the worker process handles several jobs and not just one before it ends...

**Comment by dstepe** [comment]
@shlomo-shalev are you using this [Laravel client package](https://github.com/arkaitzgarro/elastic-apm-laravel) for APM? I thought we had tested queue worker processes with that package and it was handling them.

**Comment by shlomo-shalev** [comment]
> @shlomo-shalev are you using this [Laravel client package](https://github.com/arkaitzgarro/elastic-apm-laravel) for APM? I thought we had tested queue worker processes with that package and it was handling them.

No, I previously switched to using the agent directly because the ability to add labels (setTags) and to the spans I created for monitoring elasticsearch queries did not work for me. 
But I managed to fix the problem, I just had to create a new agent object after sending the transaction.
